### ISSUE TITLE
Error while reproducing the paper

### ISSUE THREAD

**Issue by pwoznicki** [cirmuw/dynamicmemory#1]
Hello, 
I was trying to rerun your experiment and got stuck on the training using:
`python run_training.py --paper`

```
I'm getting the following error:
File "run_training.py", line 147, in <module>  
     train_paper()  
  File "run_training.py", line 28, in train_paper
    dmodel.trained_model(params['trainparams'], params['settings'])
AttributeError: module 'dynamicmemory.DynamicMemoryModel' has no attribute 'trained_model' 
```

should it maybe use `trained_model()` instead of `dmodel.trained_model()`?
Help would be much appreciated, thanks.

**Comment by mperkonigg** [comment]
Hi!
Thank you for pointing this out.
You are right, it should read trained_model() in line 28. I pushed a bugfix for this issue!

**Comment by mperkonigg** [comment]
Hi!
Thank you for pointing this out.
You are right line 28 should read trained_model(). I pushed a bugfix for that issue.
